export const ROUTER = {
  LOGIN: '/register',
  USER_LOGIN: '/login',
  NOT_FOUND: '*',
  ADMIN: '/admin',
  PRODUCTS: 'products/',
  CATEGORIES: 'categories/',
  ORDERS: 'orders',
  ORDERS_WAITING: 'orders-waiting',
  ACCEPTED_ORDERS: 'accepted-orders',
  ONTHEWAY_ORDERS: 'on-the-way-orders',
  STATISTICS: 'statistics',
  STAFF: 'staff/',
  ROLES: 'roles',
  CREATE: 'create',
  EDIT: 'edit',
  SETTINGS: 'settings',
  DETAIL: 'detail',
  ARCHIVE: 'archive',
  RE_CALL: 're-call',
  EVENTS: 'events/',
  RESERVATIONS: 'reservations/',
};
